#!/usr/bin/env node
// Convert sql-wasm.wasm to a base64-embedded JS module so we don't need
// bun --compile --assets (which is broken in bun 1.3.14).
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const pkgPath = require.resolve('sql.js/package.json')
const src = join(dirname(pkgPath), 'dist', 'sql-wasm.wasm')
const buf = readFileSync(src)
const base64 = buf.toString('base64')

const __dirname = dirname(fileURLToPath(import.meta.url))
const dest = join(__dirname, '..', 'server', 'wasm-binary.js')

writeFileSync(dest, `// Auto-generated by scripts/embed-wasm.mjs — DO NOT EDIT
// sql-wasm.wasm embedded as base64 to avoid bun --assets bug (bun 1.3.14)
const WASM_BASE64 = "${base64}";
function getWasmBinary() {
  const binaryString = atob(WASM_BASE64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes.buffer;
}
module.exports = { getWasmBinary };
`)
console.log(`✅ WASM embedded: ${buf.length} bytes → ${dest}`)
